#!/bin/bash

OUTPUT_DIR="./bin" #TODO: Ue this instead of hardcoded ./bin

if [ -z "$1" ]
  then
    echo Passe o nome do arquivo SEM EXTENSÃO como parâmetro
    exit 1
fi

if [ ! -d "$OUTPUT_DIR" ]
  then
    mkdir "$OUTPUT_DIR"
fi

gcc $1.c -Wall -o ./bin/$1.out

./bin/$1.out
